channels:
  - conda-forge
  - bioconda
dependencies:
  - docopt>=0.6.2
  - numpy>=1.10
  - pandas>=0.18
  - scipy>=0.17
  - configobj>=5.0.6
  - biopython>=1.68
  - art
  - pyfastx
  - fqtools
  - simlord
  - nanosim-h