#!/usr/bin/env Rscript

# This script creates an OTU table from the files generated by
# MGSIM communities

args = commandArgs(trailingOnly=TRUE)


# test if there is at least one argument: if not, return an error
if (length(args)<2) {
  stop("Usage:\n\totu_tab.R <community_abundance_file> <OTU_table>", call.=FALSE)
}

# OTU table creation
df = read.table(args[1], header=TRUE)

communities = sort(unique(df$Community))
taxa = sort(unique(df$Taxon))
OTU = data.frame(Taxon = taxa)

for (co in communities) {
  tmp_OTU = df[df$Community == co, c("Taxon", "Perc_rel_abund")]
  pos = match(OTU$Taxon, tmp_OTU$Taxon)
  OTU$tmp_com = tmp_OTU[pos, "Perc_rel_abund"]
  colnames(OTU)[length(colnames(OTU))] = paste("Community_", co, sep = "")
}

write.table(OTU, file=args[2], row.names=FALSE, col.names = T, sep = "\t", quote = F)